// Generated by gencpp from file rand_stu/stu_message.msg
// DO NOT EDIT!


#ifndef RAND_STU_MESSAGE_STU_MESSAGE_H
#define RAND_STU_MESSAGE_STU_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rand_stu
{
template <class ContainerAllocator>
struct stu_message_
{
  typedef stu_message_<ContainerAllocator> Type;

  stu_message_()
    : name()
    , age(0)
    , last_name()
    , department()  {
    }
  stu_message_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , last_name(_alloc)
    , department(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int8_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_name_type;
  _last_name_type last_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _department_type;
  _department_type department;





  typedef boost::shared_ptr< ::rand_stu::stu_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rand_stu::stu_message_<ContainerAllocator> const> ConstPtr;

}; // struct stu_message_

typedef ::rand_stu::stu_message_<std::allocator<void> > stu_message;

typedef boost::shared_ptr< ::rand_stu::stu_message > stu_messagePtr;
typedef boost::shared_ptr< ::rand_stu::stu_message const> stu_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rand_stu::stu_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rand_stu::stu_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rand_stu::stu_message_<ContainerAllocator1> & lhs, const ::rand_stu::stu_message_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.last_name == rhs.last_name &&
    lhs.department == rhs.department;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rand_stu::stu_message_<ContainerAllocator1> & lhs, const ::rand_stu::stu_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rand_stu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rand_stu::stu_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rand_stu::stu_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rand_stu::stu_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rand_stu::stu_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rand_stu::stu_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rand_stu::stu_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rand_stu::stu_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64bbd1451ffce53d77c080a112ddaa04";
  }

  static const char* value(const ::rand_stu::stu_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64bbd1451ffce53dULL;
  static const uint64_t static_value2 = 0x77c080a112ddaa04ULL;
};

template<class ContainerAllocator>
struct DataType< ::rand_stu::stu_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rand_stu/stu_message";
  }

  static const char* value(const ::rand_stu::stu_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rand_stu::stu_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int8 age\n"
"string last_name\n"
"string department\n"
;
  }

  static const char* value(const ::rand_stu::stu_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rand_stu::stu_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.last_name);
      stream.next(m.department);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stu_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rand_stu::stu_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rand_stu::stu_message_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int8_t>::stream(s, indent + "  ", v.age);
    s << indent << "last_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_name);
    s << indent << "department: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.department);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAND_STU_MESSAGE_STU_MESSAGE_H
