// Generated by gencpp from file rand_stu/Student.msg
// DO NOT EDIT!


#ifndef RAND_STU_MESSAGE_STUDENT_H
#define RAND_STU_MESSAGE_STUDENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rand_stu
{
template <class ContainerAllocator>
struct Student_
{
  typedef Student_<ContainerAllocator> Type;

  Student_()
    : name()
    , age(0)
    , last_name()
    , departement()  {
    }
  Student_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , last_name(_alloc)
    , departement(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int8_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_name_type;
  _last_name_type last_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _departement_type;
  _departement_type departement;





  typedef boost::shared_ptr< ::rand_stu::Student_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rand_stu::Student_<ContainerAllocator> const> ConstPtr;

}; // struct Student_

typedef ::rand_stu::Student_<std::allocator<void> > Student;

typedef boost::shared_ptr< ::rand_stu::Student > StudentPtr;
typedef boost::shared_ptr< ::rand_stu::Student const> StudentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rand_stu::Student_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rand_stu::Student_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rand_stu::Student_<ContainerAllocator1> & lhs, const ::rand_stu::Student_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.last_name == rhs.last_name &&
    lhs.departement == rhs.departement;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rand_stu::Student_<ContainerAllocator1> & lhs, const ::rand_stu::Student_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rand_stu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rand_stu::Student_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rand_stu::Student_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rand_stu::Student_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rand_stu::Student_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rand_stu::Student_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rand_stu::Student_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rand_stu::Student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5f20cbe37044f90b1f7b81f0cb5423e";
  }

  static const char* value(const ::rand_stu::Student_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5f20cbe37044f90ULL;
  static const uint64_t static_value2 = 0xb1f7b81f0cb5423eULL;
};

template<class ContainerAllocator>
struct DataType< ::rand_stu::Student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rand_stu/Student";
  }

  static const char* value(const ::rand_stu::Student_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rand_stu::Student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int8 age\n"
"string last_name\n"
"string departement\n"
;
  }

  static const char* value(const ::rand_stu::Student_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rand_stu::Student_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.last_name);
      stream.next(m.departement);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Student_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rand_stu::Student_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rand_stu::Student_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int8_t>::stream(s, indent + "  ", v.age);
    s << indent << "last_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_name);
    s << indent << "departement: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.departement);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAND_STU_MESSAGE_STUDENT_H
